# Loads default set of integrations. Do not remove.
default_config:

# Log config
logger:
  default: warning

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml

script: !include scripts.yaml
script manual: !include_dir_named scripts/

scene: !include scenes.yaml
