blueprint:
  name: Binary turns off light
  description: Turns off the light when presence is not detected.
  domain: automation
  source_url: https://github.com/estevao90/home-assistant-tweaks
  author: Estevão Costa
  input:
    presence_entity:
      name: Presence Sensor
      selector:
        entity:
          filter:
            device_class: presence
            domain: binary_sensor
    # TODO: Support multiple lights
    light_target:
      name: Light
      selector:
        entity:
          filter:
            domain: light
    no_presence_wait:
      name: Wait time
      description: Time to leave the light on after last presence is detected.
      default: 180
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: single

trigger:
  - platform: state
    entity_id: !input light_target
    from: "off"
    to: "on"
    for:
      seconds: !input no_presence_wait
  - platform: state
    entity_id: !input presence_entity
    from: "on"
    to: "off"
    for:
      seconds: !input no_presence_wait

condition:
  - condition: state
    entity_id: !input presence_entity
    state: "off"
  - condition: state
    entity_id: !input light_target
    state: "on"

action:
  - service: light.turn_off
    target:
      entity_id: !input light_target
