blueprint:
  name: Motion and illuminance light control
  description: Controls a light set based on motion and illuminance.
  domain: automation
  source_url: https://github.com/estevao90/home-assistant-tweaks
  author: Estevão Costa
  input:
    input_presence_entity:
      name: Presence Sensor
      selector:
        entity:
          filter:
            device_class: presence
            domain: binary_sensor
    input_illuminance_entity:
      name: Illuminance Sensor
      selector:
        entity:
          filter:
            device_class: illuminance
    input_lights_target:
      name: Lights
      selector:
        target:
          entity:
            domain: light
    input_illuminance_threshold:
      name: Illuminance Threshold
      description: Maximum illuminance value where the lights should stay on.
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: lx

mode: single

trigger_variables:
  presence_entity: !input input_presence_entity
  illuminance_entity: !input input_illuminance_entity
  illuminance_threshold: !input input_illuminance_threshold

trigger:
  - platform: state
    entity_id: !input input_presence_entity
  - platform: numeric_state
    entity_id: !input input_illuminance_entity
    below: !input input_illuminance_threshold

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input input_presence_entity
            state: "on"
          - condition: numeric_state
            entity_id: !input input_illuminance_entity
            below: !input input_illuminance_threshold
        sequence:
          - service: light.turn_on
            target: !input input_lights_target
    default:
      - service: light.turn_off
        target: !input input_lights_target
